services:
  client:
    image: docker-manager-client:${BUILD_NUMBER}
    container_name: docker-manager-client
    ports:
      - "86:80"
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata