package com.umeshsolanki.dockermanager

import org.slf4j.LoggerFactory
import java.io.File

object JamesSetupService {
    private val logger = LoggerFactory.getLogger(JamesSetupService::class.java)

    private val tlsConfig = """
        <tls socketTLS="false" startTLS="true">
            <privateKey>file://conf/privkey.pem</privateKey>
            <certificates>file://conf/fullchain.pem</certificates>
        </tls>
    """.trimIndent()

    private val tlsSslConfig = """
        <tls socketTLS="true" startTLS="false">
            <privateKey>file://conf/privkey.pem</privateKey>
            <certificates>file://conf/fullchain.pem</certificates>
        </tls>
    """.trimIndent()

    private val defaults = mapOf(
        "james-database.properties" to """
            # This file is generated by UCpanel
            database.driverClassName=org.apache.derby.jdbc.EmbeddedDriver
            database.url=jdbc:derby:../var/store/derby;create=true
            database.username=app
            database.password=app
            vendorAdapter.database=DERBY
        """.trimIndent(),

        "usersrepository.xml" to """
            <?xml version="1.0"?>
            <usersrepository name="LocalUsersRepository">
                <repository name="LocalUsersRepository" class="org.apache.james.user.jpa.JPAUsersRepository">
                    <algorithm>MD5</algorithm>
                    <enableVirtualHosting>true</enableVirtualHosting>
                </repository>
            </usersrepository>
        """.trimIndent(),

        "domainlist.xml" to """
            <?xml version="1.0"?>
            <domainlist name="JPADomainList">
                <domainnames>
                    <domainname>localhost</domainname>
                </domainnames>
                <autodetect>true</autodetect>
                <autodetectIP>true</autodetectIP>
                <defaultDomain>localhost</defaultDomain>
            </domainlist>
        """.trimIndent(),

        "smtpserver.xml" to """
            <?xml version="1.0"?>
            <smtpservers>
                <smtpserver enabled="true">
                    <jmxName>smtpserver</jmxName>
                    <bind>0.0.0.0:25</bind>
                    $tlsConfig
                    <auth>
                        <announce>true</announce>
                    </auth>
                </smtpserver>
                <smtpserver enabled="true">
                    <jmxName>smtpserver-tls</jmxName>
                    <bind>0.0.0.0:465</bind>
                    $tlsSslConfig
                    <auth>
                        <announce>always</announce>
                    </auth>
                </smtpserver>
                <smtpserver enabled="true">
                    <jmxName>smtpserver-submission</jmxName>
                    <bind>0.0.0.0:587</bind>
                    $tlsConfig
                    <auth>
                        <announce>always</announce>
                    </auth>
                </smtpserver>
            </smtpservers>
        """.trimIndent(),

        "imapserver.xml" to """
            <?xml version="1.0"?>
            <imapservers>
                <imapserver enabled="true">
                    <jmxName>imapserver</jmxName>
                    <bind>0.0.0.0:143</bind>
                    $tlsConfig
                </imapserver>
                <imapserver enabled="true">
                    <jmxName>imapserver-ssl</jmxName>
                    <bind>0.0.0.0:993</bind>
                    $tlsSslConfig
                </imapserver>
            </imapservers>
        """.trimIndent(),

        "lmtpserver.xml" to """
            <?xml version="1.0"?>
            <lmtpservers>
                <lmtpserver enabled="true">
                    <jmxName>lmtpserver</jmxName>
                    <bind>0.0.0.0:24</bind>
                </lmtpserver>
            </lmtpservers>
        """.trimIndent()
    )

    fun initialize() {
        val configDir = AppConfig.jamesConfigDir
        if (!configDir.exists()) {
            configDir.mkdirs()
        }

        defaults.forEach { (filename, content) ->
            ensureFile(configDir, filename, content)
        }
        
        // Ensure var directory exists
        val varDir = AppConfig.jamesVarDir
        if (!varDir.exists()) {
            varDir.mkdirs()
        }
    }

    fun getDefaultContent(filename: String): String? {
        return defaults[filename]
    }

    fun listDefaultFiles(): List<String> {
        return defaults.keys.toList()
    }

    private fun ensureFile(dir: File, filename: String, content: String) {
        val file = File(dir, filename)
        if (!file.exists()) {
            logger.info("Generating default James configuration: ${'$'}filename")
            file.writeText(content)
        }
    }
}
