package com.umeshsolanki.dockermanager

import org.slf4j.LoggerFactory
import java.io.File

object JamesSetupService {
    private val logger = LoggerFactory.getLogger(JamesSetupService::class.java)

    fun initialize() {
        val configDir = AppConfig.jamesConfigDir
        if (!configDir.exists()) {
            configDir.mkdirs()
        }

        ensureFile(configDir, "james-database.properties", """
            # This file is generated by UCpanel
            database.driverClassName=org.apache.derby.jdbc.EmbeddedDriver
            database.url=jdbc:derby:../var/store/derby;create=true
            database.username=app
            database.password=app
            vendorAdapter.database=DERBY
        """.trimIndent())

        ensureFile(configDir, "usersrepository.xml", """
            <?xml version="1.0"?>
            <usersrepository name="LocalUsersRepository">
                <repository name="LocalUsersRepository" class="org.apache.james.user.jpa.JPAUsersRepository">
                    <algorithm>MD5</algorithm>
                </repository>
            </usersrepository>
        """.trimIndent())

        ensureFile(configDir, "domainlist.xml", """
            <?xml version="1.0"?>
            <domainlist name="JPADomainList">
                <domainnames>
                    <domainname>localhost</domainname>
                </domainnames>
                <autodetect>true</autodetect>
                <autodetectIP>true</autodetectIP>
                <defaultDomain>localhost</defaultDomain>
            </domainlist>
        """.trimIndent())
        
        // Ensure var directory exists
        val varDir = AppConfig.jamesVarDir
        if (!varDir.exists()) {
            varDir.mkdirs()
        }
    }

    private fun ensureFile(dir: File, filename: String, content: String) {
        val file = File(dir, filename)
        if (!file.exists()) {
            logger.info("Generating default James configuration: $filename")
            file.writeText(content)
        }
    }
}
